export const AUTH_TOKEN = "3773f421e0de8bae3c97312044ad4791bc0a00e7";
export const USER_EMAIL = "f20170635@pilani.bits-pilani.ac.in";

export const GET_CAPTIONS = "GET_CAPTIONS";
export const GET_CAPTIONS_SUCCESS = "GET_CAPTIONS_SUCCESS";
export const GET_CAPTIONS_FAIL = "GET_CAPTIONS_FAIL";

export const POST_REACTION = "POST_REACTION";
export const POST_REACTION_SUCCESS = "POST_REACTION_SUCCESS";
export const POST_REACTION_FAIL = "POST_REACTION_FAIL";

export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const POST_NEW_COMMENT = "POST_NEW_COMMENT";
export const POST_NEW_COMMENT_SUCCESS = "POST_NEW_COMMENT_SUCCESS";
export const POST_NEW_COMMENT_FAIL = "POST_NEW_COMMENT_FAIL";

export const FETCH_LINK_PREVIEWS = "FETCH_LINK_PREVIEWS";

export const GET_COMPLETE_PROFILE = "GET_COMPLETE_PROFILE";
export const GET_COMPLETE_PROFILE_SUCCESS = "GET_COMPLETE_PROFILE_SUCCESS";
export const GET_COMPLETE_PROFILE_FAIL = "GET_COMPLETE_PROFILE_FAIL";

export const POST_FRIEND_REQUEST = "POST_FRIEND_REQUEST";
export const POST_FRIEND_REQUEST_SUCCESS = "POST_FRIEND_REQUEST_SUCCESS";
export const POST_FRIEND_REQUEST_FAIL = "POST_FRIEND_REQUEST_FAIL";

export const POST_MESSAGE_REQUEST = "POST_MESSAGE_REQUEST";
export const POST_MESSAGE_REQUEST_SUCCESS = "POST_MESSAGE_REQUEST_SUCCESS";
export const POST_MESSAGE_REQUEST_FAIL = "POST_MESSAGE_REQUEST_FAIL";

export const POST_HANGOUT_REQUEST = "POST_HANGOUT_REQUEST";
export const POST_HANGOUT_REQUEST_SUCCESS = "POST_HANGOUT_REQUEST_SUCCESS";
export const POST_HANGOUT_REQUEST_FAIL = "POST_HANGOUT_REQUEST_FAIL";

export const GET_RELATIONSHIP = "GET_RELATIONSHIP";
export const GET_RELATIONSHIP_SUCCESS = "GET_RELATIONSHIP_SUCCESS";
export const GET_RELATIONSHIP_FAIL = "GET_RELATIONSHIP_FAIL";

export const ALL_USERS = "GET_ALL_USERS";
export const ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const ADD_TO_SEEN = "ADD_TO_SEEN";
export const REMOVE_FROM_UNSEEN = "REMOVE_FROM_UNSEEN";

export const MARK_AS_READ = "MARK_AS_READ";
export const MARK_AS_READ_FAIL = "MARK_AS_READ_FAIL";

export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";
export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";

export const IGNORE_NOTIF = "IGNORE_NOTIF";

export const STORE_AUTH = "STORE_AUTH";
export const GET_PROFILE_COMPLETION_STATE = "GET_PROFILE_COMPLETION_STATE";
